### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by lus** [zekroTJA/vctr#12]
I try to create a user with the name `test` and everytime I click on `Create` I get an unexpected error. If I look into the console, I get an error 400.

My docker-compose file:
```yml
version: "3"

services:
  x0-db:
    image: "postgres"
    container_name: "x0-db"
    restart: always
    expose:
      - "5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "vctr"
      POSTGRES_PASSWORD: "nope"
    networks:
      - "x0"

  x0-redis:
    image: "redis"
    container_name: "x0-redis"
    restart: always
    expose: 
      - "6379"
    networks:
      - "x0"

  x0-gw:
    build:
      context: './src/'
      dockerfile: './Gateway/Dockerfile'
    image: "zekro/vctr-gw"
    restart: always
    expose: 
      - "80"
    environment:
      VCTR_CONNECTIONSTRINGS__POSTGRES: "Host=x0-db;Database=vctr;Username=vctr;Password=nope"
      VCTR_INITIALIZATION__ROOTUSERNAME: "nope"
      VCTR_INITIALIZATION__ROOTUSERPASSWORD: "nope"
      VCTR_CACHING__DURATION: "30.00:00:00"
      VCTR_CACHING__REDIS__SERVERS: "x0-redis:6379"
      VCTR_CACHING__REDIS__DATABASE: 2
      VCTR_ROUTING__ROOT: "https://x0.tf"
      VCTR_ROUTING__NOTFOUND: "/ui/notfound"
      VCTR_ROUTING__PASSWORD: "/ui/password"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.x0-gw.rule=Host(`x0.tf`)"
      - "traefik.http.routers.x0-gw.entrypoints=web-secured"
      - "traefik.http.routers.x0-gw.tls"
    networks: 
      - "x0"
      - "web"  

  x0-fe:
    build:
      context: './src/'
      dockerfile: './WebApp/Dockerfile'
    image: "zekro/vctr-fe"
    restart: always
    expose: 
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.x0-fe.rule=Host(`x0.tf`) && PathPrefix(`/ui`)"
      - "traefik.http.routers.x0-fe.entrypoints=web-secured"
      - "traefik.http.routers.x0-fe.tls"
      - "traefik.http.routers.x0-fe.middlewares=x0-fe-stripprefix"
      - "traefik.http.middlewares.x0-fe-stripprefix.stripprefix.prefixes=/ui/"
    networks: 
      - "x0"
      - "web"  

networks:
  x0:
    driver: bridge
  web:
    external:
      name: web
```
